# Generated by Django 5.2.10 on 2026-02-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(default='+996 ', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
