# Generated by Django 5.0.4 on 2026-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0003_alter_announcement_options_announcementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
    ]
