# Generated by Django 5.0.4 on 2026-05-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0004_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='announcementimage',
            options={},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(max_length=135, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/gallery/'),
        ),
    ]
