# Generated by Django 5.0.4 on 2026-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0006_alter_announcement_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementimage',
            options={'verbose_name': 'Фотография галереи', 'verbose_name_plural': 'Фотографии галереи'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_photos/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
