# Generated by Django 5.0.4 on 2026-05-17 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0007_alter_announcementimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01, message='Цена должна быть больше нуля!')], verbose_name='Цена'),
        ),
    ]
