# Generated by Django 5.0.4 on 2026-05-18 08:50

import anons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0008_alter_announcement_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=anons.models.get_main_photo_path, validators=[anons.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=anons.models.get_gallery_photo_path, validators=[anons.models.validate_image_size]),
        ),
    ]
