# Generated by Django 5.0.4 on 2026-05-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0009_alter_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01, message='Цена должна быть больше нуля!')], verbose_name='Цена'),
        ),
    ]
